# EJ1 - CREA UN USUARIO system CON CONTRASEÑA 'efd5r26' QUE QUE PUEDA CONECTARSE DESDE CUALQUIER MAQUINA AL SERVIDOR MYSQL 
#       Y QUE TENGA TODOS LOS PRIVILEGIOS SOBRE TODOS LOS OBJETOS DE MYSQL (IGUAL QUE ROOT). TENED EN CUENTA QUE ESTE USUARIO VA A TENER QUE CONCEDER DISTINTOS PRIVILEGIOS A OTROS USUARIOS. 
#     - CREA UNA CONEXION CON EL USUARIO system. HAZ EL RESTO DE APARTADOS USANDO ESTE USUARIO. 

CREATE USER 'system' IDENTIFIED BY 'efd5r26';
# CREA LOS USUARIOS

GRANT ALL PRIVILEGES ON *.* TO 'system' WITH GRANT OPTION; 
# DA TODOS LOS PRIVILEGIOS DEL SITEMA

FLUSH PRIVILEGES; #UPDATE DE PRIVILEGIOS

# EJ2 - CREA USUARIO LLAMADO dependiente_basico CON CONTRASEÑA '1234' QUE PUEDA CONECTARSE DESDE CUALQUIER MAQUINA AL MYSQL.
#     - DALE A dependiente_basico PERMISOS CONSULTA E INSERCION SOBRE LA TABLAS payment, rental Y customer DE LA BASE DE DATOS SAKILA. 
#     - DALE A dependiente_basico PERMISOS PARA QUE EJECUTE TODOS LOS PROCEDIMIENTOS Y FUNCIONES DE LA BASE DE DATOS SAKILA. 

CREATE USER 'dependiente_basico'  IDENTIFIED BY '1234';

GRANT SELECT, INSERT, UPDATE ON SAKILA.PAYMENT TO 'dependiente_basico';
GRANT SELECT, INSERT, UPDATE ON SAKILA.RENTAL TO 'dependiente_basico';
GRANT SELECT, INSERT, UPDATE ON SAKILA.CUSTOMER TO 'dependiente_basico';

GRANT EXECUTE ON SAKILA.* TO 'dependiente_basico';  

SELECT * FROM MYSQL.USER;

SHOW GRANTS FOR 'dependiente_basico';

# EJ3 - CREA UN USUARIO LLAMADO mto_catalogo CON CONTRASEÑA '5678' QUE PUEDA CONECTARSE DESDE CUALQUIER MAQUINA AL MYSQL.
#     - DALE A mto_catalogo PERMISOS DE INSERCION , MODIFICACION Y BORRADO SOBRE LAS TABLAS film , actor, category, film_actor y film_text. TAMBIEN PERMISO DE MODIFICACION DE LA ESTRUCTURA DE LAS TABLAS (por ejemplo, para que puedan añadir campos nuevos) 
#     - CREA UNA CONEXION CON EL USUARIO mto_catalogo Y AÑADE EN CAMPO director (tipo char)  A LA TABLA film DESDE EL USUARIO mto_catalogo.

CREATE USER 'mto_catalogo' IDENTIFIED BY '5678';

GRANT INSERT, UPDATE, DELETE, ALTER ON SAKILA.FILM TO 'mto_catalogo';
GRANT INSERT, UPDATE, DELETE, ALTER ON SAKILA.ACTOR TO 'mto_catalogo';
GRANT INSERT, UPDATE, DELETE, ALTER ON SAKILA.CATEGORY TO 'mto_catalogo';
GRANT INSERT, UPDATE, DELETE, ALTER ON SAKILA.FILM_ACTOR TO 'mto_catalogo';
GRANT INSERT, UPDATE, DELETE, ALTER ON SAKILA.FILM_TEXT TO 'mto_catalogo';

SHOW GRANTS FOR 'mto_catalogo';

# EJ4 - CREA UN ROL supervisor_consulta  QUE TENGA PERMISOS PARA CONSULTAR TODAS TABLAS DE LA BASE DE DATOS SAKILA Y SEGUROS. 
#     - CREA UN ROL propietario QUE TENGA LOS PERMISOS ANTERIORES Y QUE ADEMAS PUEDA AÑADIR , MODIFICAR Y BORRAR DATOS DE 
#       LAS TABLAS DE SAKILA Y SEGUROS.
  
CREATE ROLE 'supervisor_consulta';

GRANT SELECT ON world.* TO 'supervisor_consulta';
GRANT SELECT ON sakila.* TO 'supervisor_consulta';

CREATE ROLE 'propietario';

GRANT 'supervisor_consulta' TO 'propietario'; # LOS DEL PROPIETARIO A SUPERVISOR

GRANT UPDATE, DELETE, ALTER ON seguros.* TO 'propietario';
GRANT UPDATE, DELETE, ALTER ON sakila.* TO 'propietario';
  
SHOW GRANTS FOR 'mto_catalogo';
  
# EJ5 - CREA UN USUARIO dueno QUE TENGA EL ROL DE propietario Y QUE PUEDA CONCEDER DICHO ROL A OTRO USUARIO.
#     - CREA UN USUARIO hijo_dueno. HACER QUE SU PADRE LE CONCEDA EL ROL DE PROPIETARIO.

