# -----------------------------------------------------
#						FUNCIONES
# -----------------------------------------------------

# CONCAT () -> CONCATENA CADENAS DE CARACTERES

USE WORLD;
SELECT
	NAME,
    CONCAT(CONTINENT, "-", REGION) AS CONTREGION
FROM COUNTRY; 

# LOWER() -> LO PONE EN MINISCULA   
# UPPER() -> LO PONE EN MAYUSCULA

SELECT LOWER(NAME) FROM COUNTRY;
SELECT UPPER(NAME) FROM COUNTRY;


# LEFT(cadena, n) -> n PRIMEROS CARECTERES
# RIGHT(cadena, n) -> n ULTIMOS CARACTERES
# MID(cadena, p, n) O SUBSTR()-> n CARACTERES DESDE LA POSICION p

SELECT LEFT("CADENA DE TEXTO", 5);
SELECT RIGHT("CADENA DE TEXTO", 5);
SELECT MID("CADENA DE TEXTO", 8 , 2);

SELECT UPPER(LEFT(NAME, 3)) FROM COUNTRY;


# EJ67 SELECIONA EL CÓDIGO DE LOS PAÍSES, LAS 3 PRIMERAS LETRAS DE SU NOMBRE EN MAYUSCULA Y UNA COLUMNA QUE INDIQUE SI LAS DOS ANTERIORES COINCIDEN

SELECT 
	CODE,
    UPPER(LEFT (NAME, 3)) AS TRES_PRIMERAS,
    CODE=LEFT (NAME, 3) AS IGUALES
FROM COUNTRY;

# EJ68 ¿CUANTOS PAISES COINCIDE EL CODIGO CON LAS TRES PRIMERAS LETRAS DE SU NOMBRE?

SELECT 
	COUNT(*)
FROM COUNTRY
WHERE CODE=UPPER(LEFT (NAME, 3));


# REPEAT (cadena, n) -> REPITE UNA cadena n VECES

SELECT REPEAT("*", 8);
  
SELECT REPEAT(NAME, 80) FROM COUNTRY;

# REPLACE(cadena, subcadena_anterior, subcadena_nueva)

SELECT REPLACE ("ESTO ES UNA CADENA DE TEXTO CADENA", "CADENA", "OTRA COSA");

SELECT REPLACE(HEADOFSTATE, "Elisabeth", "Isabel") FROM COUNTRY;

# REVERSE -> INVIERTE UNA CADENA DE TEXTO

SELECT REVERSE("123456789");

SELECT REVERSE(GovernmentForm) FROM COUNTRY;


# ============================================================================
#                      		  FUNCONES NUMERICAS
# ============================================================================

# RAIZ CUADRADA: SQRT()

SELECT SQRT(9);


# EJ69 ¿SI ESPAÑA FUESE UN CUADRADO, CUANTOS KILOMETROS DE LADO TENDRÍA?

SELECT SQRT(SURFACEAREA) FROM COUNTRY WHERE CODE = "ESP";

# POW () ELEVAR 

SELECT POW(2,10); 

# RAND() -> NUMERO ALEATORIO ENTRE 0 Y 1

SELECT TRUNCATE(RAND()*10+1, 0);
SELECT CEIL(RAND()*10);

# ROUND(numero, decimales) -> REDONDEAR
# TRUNCATE(numero, decimales) -> TRUNCA
# FLOOR(numero) -> ENTERO INFERIOR SON MUY PARECIDOS
# CEIL(numero) -> ENTERO SUPERIOR

SELECT ROUND(7.896599568, 2);
SELECT TRUNCATE(7.896599568, 1);
SELECT FLOOR(7.896599568);
SELECT CEIL(7.1);
