USE WORLD;

# ====================================================================
#								JOIN
# ====================================================================

SELECT * FROM CITY
JOIN country ON CITY.COUNTRYCODE = COUNTRY.CODE;

# EJ71 - MUESTRA UNA LISTA DE LAS CIUDADES DE ESPAÑA, SU POBLACIÓN, LA POBLACIÓN DEL PAÍS Y EL % DE POBLACIÓN DEL PAÍS QUE VIVE EN ESA CIUDAD (2 DECIMALES)

SELECT NAME, POPULATION FROM CITY WHERE COUNTRYCODE = 'ESP';

SELECT 
	CITY.NAME, 
    CITY.POPULATION,
    COUNTRY.POPULATION,
    ROUND(CITY.POPULATION/COUNTRY.POPULATION*100,2) AS POBLACION_EN_CIUDAD
FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.NAME = "SPAIN";

# EJ72 - MUESTRA UNA LISTA DE LOS DISTRITOS DE ESPAÑA, SU POBLACIÓN, LA POBLACIÓN DEL PAÍS Y EL PORCENTAJE DE POBLACIÓN DEL PAÍS QUE VIVE EN ESE DISTRITO (2 DECIMALES)

SELECT 
    CITY.DISTRICT,
    SUM(CITY.POPULATION) AS DISTRITO_POBLACION,
    COUNTRY.POPULATION AS PAIS_POBLACION,
    ROUND(SUM(CITY.POPULATION)/COUNTRY.POPULATION*100,2) AS PORCENTAJE_POBLACION_EN_DISTRITO
FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.NAME = 'SPAIN'
GROUP BY CITY.DISTRICT, COUNTRY.POPULATION;


# EJ73 - MUESTRA UNA LISTA DE LOS NOMBRES DE LAS CAPITALES EUROPEAS.

SELECT 
	CITY.NAME
FROM COUNTRY
JOIN CITY ON COUNTRY.CAPITAL = CITY.ID
WHERE COUNTRY.CONTINENT = "EUROPE";

# EJ74 - ¿CUÁL ES LA CAPITAL DEL MUNDO MÁS POBLADA?

SELECT 
	CITY.NAME
FROM COUNTRY
JOIN CITY ON COUNTRY.CAPITAL = CITY.ID
ORDER BY CITY.POPULATION DESC
LIMIT 1;

# EJ75 - MUESTRA UNA LISTA CON EL NOMBRE DE LOS PAÍSES Y LA CANTIDAD DE IDIOMAS QUE SE HABLAN EN DICHO PAÍS.

SELECT 
	CO.NAME,
    COUNT(CL.LANGUAGE) AS IDIOMAS
FROM COUNTRY AS CO
JOIN COUNTRYLANGUAGE AS CL ON CO.CODE=CL.COUNTRYCODE
GROUP BY CO.NAME;

# EJ76 - MUESTRA UNA LISTA CON EL NOMBRE DE LOS PAÍSES Y LA CANTIDAD DE IDIOMAS OFICIALES QUE SE HABLAN EN DICHO PAÍS.

SELECT 
	CO.NAME,
    COUNT(CL.LANGUAGE) AS IDIOMAS
FROM COUNTRY AS CO
JOIN COUNTRYLANGUAGE AS CL ON CO.CODE=CL.COUNTRYCODE
WHERE CL.ISOFFICIAL = "T"
GROUP BY CO.NAME;

# EJ77 - MUESTRA UNA LISTA CON EL NOMBRE DE TODOS LOS PAÍSES Y LA CANTIDAD DE CIUDADES DE CADA PAÍS DISPONIBLES EN LA BASE DE DATOS.

SELECT
	CO.NAME,
    COUNT(*) AS CIUDADES
FROM CITY AS CI
JOIN COUNTRY AS CO ON CI.COUNTRYCODE=CO.CODE
GROUP BY CO.NAME;

# EJ78 - MUESTRA EL NOMBRE DE LOS PAÍSES SIN CIUDADES REGISTRADAS.

SELECT NAME FROM COUNTRY
WHERE CODE NOT IN (SELECT COUNTRYCODE FROM CITY);

SELECT
	CO.NAME
FROM COUNTRY AS CO
LEFT JOIN CITY AS CI ON CI.COUNTRYCODE=CO.CODE
WHERE CI.NAME IS NULL;

# EJ79 - MUESTRA UNA LISTA CON EL NOMBRE DE LOS PAÍSES, LOS IDIOMAS HABLADOS Y LA CANTIDAD DE PERSONAS QUE HABLAN CADA IDIOMA EN CADA PAÍS.

SELECT 
	CO.NAME,
    CL.LANGUAGE,
    CO.POPULATION*CL.PERCENTAGE/100 AS HABLANTES
FROM COUNTRY AS CO
JOIN COUNTRYLANGUAGE AS CL ON CO.CODE=CL.COUNTRYCODE;

# EJ80 - MUESTRA UNA LISTA CON EL NOMBRE DE LA CAPITAL DE LOS PAÍSES CON ESPAÑOL COMO IDIOMA OFICIAL.

SELECT 
	CI.NAME
FROM COUNTRY AS CO
JOIN COUNTRYLANGUAGE AS CL ON CO.CODE=CL.COUNTRYCODE
JOIN CITY CI ON CO.CAPITAL=CI.ID
WHERE CL.LANGUAGE="SPANISH" AND CL.ISOFFICIAL="T";

# EJ81 - MUESTRA EL PORCENTAJE DE LA POBLACIÓN MUNDIAL QUE HABLA ESPAÑOL.

SELECT 
    CL.LANGUAGE,
    SUM(CO.POPULATION*CL.PERCENTAGE/100)
    /
    (SELECT SUM(POPULATION) FROM COUNTRY)*100 AS HISPANOHABLANTES
FROM COUNTRY AS CO
JOIN COUNTRYLANGUAGE AS CL ON CO.CODE=CL.COUNTRYCODE
WHERE CL.LANGUAGE="ENGLISH";

# EJ82 - MUESTRA UNA LISTA CON LOS IDIOMAS Y EL PORCENTAJE DE LA POBLACIÓN MUNDIAL QUE HABLA CADA IDIOMA (ORDENA DE MAYOR A MENOR).

# EJ83 - MUESTRA TODAS LAS CIUDADES QUE NO SON CAPITALES.


