USE SAKILA;

# EJ1.- ¿CUÁLES SON LAS TARIFAS DE ALQUILER (RENTAL RATE)?

SELECT rental_rate FROM film;


# EJ2.- ¿CUÁNTAS PELÍCULAS DURAN MÁS DE 100 MINUTOS Y TIENEN UN RATING DE PG, R O G?
	
SELECT COUNT(*) FROM film WHERE length > 100 AND rating IN ('PG', 'R', 'G');

    
# EJ3.- ¿CUÁL ES LA PELÍCULA O PELÍCULAS CON MAYOR DURACIÓN DE LAS QUE CONTIENEN TRAILERS COMO EXTRAS?

SELECT TITLE, LENGTH
FROM FILM
WHERE SPECIAL_FEATURES LIKE "%Trailers%"
ORDER BY LENGTH DESC;

# EJ4.- ¿QUÉ PELÍCULAS ESTÁN PROTAGONIZADAS POR UN ASTRONAUTA Y UN ADMINSTRADOR DE BASES DE DATOS (DESCRIPTION)?

SELECT TITLE
FROM FILM
WHERE DESCRIPTION LIKE "%astronaut%"
AND DESCRIPTION LIKE "%database administrator%";

# EJ5.- ¿CUÁNTO DURAN, DE MEDIA, LAS PELÍCULAS PROTAGONIZADAS POR EL ACTOR 1 (FILM_ACTOR)?

SELECT AVG(LENGTH) AS DURACION_MEDIA
FROM FILM 
WHERE ACTOR_ID = 1;

select * from FILM_ACTOR;

-- EJ6.- ¿CUÁNTO TARDARÍAMOS (EN HORAS) EN VER TODAS LAS PELÍCULAS DE CATEGORÍA 6 (FILM_CATEGORY)?
SELECT SUM(LENGTH) AS DURACION_TOTAL_HORAS
FROM FILM
WHERE FC.CATEGORY_ID = '6';


select * from film_category;