# TODOS LOS EJERCICIOS SE DEBEN RESOLVER HACIENDO USO DE LA CLÁUSULA JOIN

USE SAKILA;

# EJ1 - SELECCIONA UNA LISTA DE LOS ACTORES (CONCATENA NOMBRE Y APELLIDOS) Y MUESTRA CUANTAS PELÍCULAS HA HECHO CADA ACTOR. ORDENA DE MAYOR A MENOR CANTIDAD DE PELÍCULAS (ACTOR Y FILM_ACTOR).

SELECT 
    CONCAT(A.FIRST_NAME, ' ', A.LAST_NAME) AS ACTORES,
    COUNT(FA.FILM_ID) AS CANTIDAD_PELICULAS
FROM 
	ACTOR A
JOIN 
    FILM_ACTOR FA ON A.ACTOR_ID = FA.ACTOR_ID
GROUP BY 
    A.ACTOR_ID  
ORDER BY
	CANTIDAD_PELICULAS DESC;
    
# EJ2 - MUESTRA UNA LISTA DE LAS PELÍCULAS Y SU IDIOMA EN MAYÚSCULA (FILM Y LANGUAGE).

SELECT * FROM FILM;

SELECT 
    F.TITLE,
    UPPER(L.NAME) AS IDIOMA
FROM 
    FILM F
JOIN 
    LANGUAGE L ON F.LANGUAGE_ID = L.LANGUAGE_ID;


# EJ3 - MUESTRA UNA LISTA DE LAS PELÍCULAS Y LA CANTIDAD DE CADA PELÍCULA QUE TENEMOS EN EL INVENTARIO (FILM E INVENTORY).

SELECT 
    F.TITLE AS TITULO_PELICULA,
    COUNT(I.INVENTORY_ID) AS CANTIDAD_EN_PELICULAS_INVENTARIO
FROM 
    FILM F
JOIN 
    INVENTORY I ON F.FILM_ID = I.FILM_ID
GROUP BY 
    F.FILM_ID
ORDER BY		
    CANTIDAD_EN_PELICULAS_INVENTARIO DESC;
    
    
SELECT * FROM INVENTORY;
	

# EJ4 - MUESTRA EL NOMBRE Y LOS APELLIDOS DEL USUARIO QUE MÁS PELÍCULAS HA ALQUILADO (CUSTOMER Y RENTAL) (USA LIMIT 1).

SELECT 
    CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS USUARIO_QUE_MAS_HA_ALQUILADO
FROM 
    CUSTOMER C
JOIN 
    RENTAL R ON C.CUSTOMER_ID = R.CUSTOMER_ID
GROUP BY 
    C.CUSTOMER_ID
ORDER BY
	C.CUSTOMER_ID DESC;


SELECT * FROM RENTAL;
SELECT * FROM CUSTOMER;
	
# EJ5 - MUESTRA UNA LISTA DE LAS CATEGORÍAS Y LA DURACIÓN MEDIA DE LAS PELÍCULAS DE CADA CATEGORÍA (FILM, CATEGORY Y FILM_CATEGORY).

SELECT 
    C.NAME AS CATEGORIA,
	AVG(F.LENGTH) AS DURACION_MEDIA_PELICULA
FROM 
    FILM F
JOIN 
    FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
GROUP BY 
    FC.FILM_ID;    

    

SELECT * FROM FILM;
SELECT * FROM CATEGORY;
SELECT * FROM FILM_CATEGORY;
