# ===================   BORRADO DE DATOS   =================== #

# BORRA TODO EL CONTENIDO DE LA TABLA
TRUNCATE TABLE CITY; # BORRADO PERMANENETE EN DISCO
DELETE FROM CITY; # NO ES PERMANENTE HASTA REALIZAR COMMIT

# BORRA LA ESTRUCTURA DE LA TABLA (INCLUIDO EL CONTENIDO)
DROP TABLE COUNTRYLANGUAGE;
DROP TABLE IF EXISTS COUNTRYLANGUAGE;

# BORRAR FILAS DETERMINADAS
DELETE FROM COUNTRYLANGUAGE WHERE COUNTRYCODE="ESP";

# ================   ACTUALIZACIÓN DE DATOS   ================ #

SELECT * FROM COUNTRY WHERE CODE="ESP";

UPDATE COUNTRY SET POPULATION=POPULATION*1.1 WHERE CODE="ESP";

# ===================   TRANSACCIONES   ====================== #

SET SQL_SAFE_UPDATES=FALSE; # DESACTIVAR MODO SEGURO (SOLO PUEDO MODIFICAR USANDO PKs EN EL WHERE)
DELETE FROM CITY;
DELETE FROM COUNTRYLANGUAGE WHERE COUNTRYCODE="ESP";

ROLLBACK; # DESHACE LA TRANSACCIÓN COMPLETA (VUELVO AL ÚLIMO ESTADO)

COMMIT; # LOS CAMBIOS SON PERMANENTES

# ====================   EJERCICIOS   ======================= #

# EJ1 - ELIMINA FRANCIA DEL PLANETA.

SELECT * FROM CITY WHERE NAME="PARIS";

DELETE FROM CITY WHERE COUNTRYCODE="FRA";
DELETE FROM COUNTRYLANGUAGE WHERE COUNTRYCODE ="FRA";
DELETE FROM COUNTRY WHERE CODE="FRA";
ROLLBACK; # SIRVE PARA RECUPERAR LO QUE HEMOS BORRADO.

# EJ2 - AUMENTA UN 10% LA POBLACIÓN DE LOS PAÍSES AFRICANOS.

SELECT * FROM COUNTRY WHERE CONTINENT="AFRICA" ;
UPDATE COUNTRY SET POPULATION=POPULATION*1.1 WHERE CONTINENT="AFRICA";

# EJ3 - FUSIONA ESPAÑA CON PORTUGAL Y LOS PAÍSES AMERICANOS. 
#       FUSIONA LA SUPERFICIE, POBLACIÓN, GNP Y ESPERANZA DE VIDA MEDIA
#       EL NUEVO PAÍS DEBE SER LLAMADO "IMPERIO ESPAÑOL".



# EJ4 - CAMBIA LA CIUDAD DE GIBRALTAR PARA QUE PASE A SER ESPAÑOLA.

SELECT * FROM CITY WHERE NAME = "Gibraltar";
UPDATE CITY SET COUNTRYCODE = 'ESP' WHERE NAME = 'Gibraltar';

# EJ5 - TODAS LAS CIUDADES DE MURCIA SON INCORPORADAS POR LA COMUNIDAD VALENCIANA.

SET SQL_SAFE_UPDATES=FALSE; # DESACTIVAR MODO SEGURO (SOLO PUEDO MODIFICAR USANDO PKs EN EL WHERE)
UPDATE CITY SET DISTRICT="VALENCIA" WHERE DISTRICT="MURCIA";

# EJ6 - CREA UNA COLUMNA NUEVA EN LA TABLA FILM QUE MUESTRE LA DURACIÓN DE LAS PELÍCULAS EN FORMATO "TIME"

USE SAKILA;

ALTER TABLE FILM ADD COLUMN (DURACION TIME);
UPDATE FILM SET DURACION=SEC_TO_TIME(LENGTH*60);

SELECT * FROM FILM;

# EJ7 - CREA UNA COLUMNA EDAD_MÍNIMA EN FILM QUE MUESTRE LA FECHA DE NACIMIENTO MÍNIMA PARA ALQUILAR LA PELÍCULA:
# G -> TODOS LOS PÚBLICOS
# PG -> MAYORES DE 7 AÑOS
# PG-13 -> MÁS DE 13 AÑOS
# R Y NC-17 -> MÁS DE 17 AÑOS

ALTER TABLE FILM ADD COLUMN (EDAD_MINIMA DATE);

UPDATE FILM SET EDAD_MINIMA=DATE_ADD(NOW(), INTERVAL -7 YEAR) WHERE RATING="PG";
UPDATE FILM SET EDAD_MINIMA=DATE_ADD(NOW(), INTERVAL -13 YEAR) WHERE RATING="PG-13";
UPDATE FILM SET EDAD_MINIMA=DATE_ADD(NOW(), INTERVAL -17 YEAR) WHERE RATING IN ("R", "NC-17");

SELECT * FROM FILM;

# EJ8 - BORRA LAS PELÍCULAS QUE DUREN MENOS DE DOS HORAS.

DELETE FROM film_actor
WHERE film_id IN (SELECT film_id FROM film WHERE DURACION < '02:00:00');

DELETE FROM film WHERE DURACION < '02:00:00';

# EJ9 - BORRA LAS PELÍCULAS QUE NO DISPONGAN DE NINGUNA COPIA EN EL INVENTARIO.

DELETE FROM FILM
WHERE FILM_ID NOT IN (SELECT DISTINCT FILM_ID FROM INVENTORY);


