USE WORLD;

# SELECCIONAR TODAS LAS COLUMNAS Y TODAS LAS FILAS

SELECT * FROM CITY;
SELECT * FROM COUNTRY;
SELECT * FROM COUNTRYLANGUAGE;

# SELECCIONAR COLUMNAS CONCRETAS PERO TODAS LAS FILAS

SELECT NAME, CONTINENT FROM COUNTRY;

# SELECCIONAR COLUMNAS CON ALIAS;

SELECT 
	NAME AS NOMBRE, 
    CONTINENT AS CONTINENTE
FROM COUNTRY;

SELECT 
	NAME AS PAIS,
    SURFACEAREA
FROM COUNTRY;

# CLÁUSULA WHERE

SELECT * FROM COUNTRY WHERE NAME = "SPAIN";

# CÁUSULA DISTINCT

SELECT DISTINCT CONTINENT FROM COUNTRY;

# EJ1 - MUESTRA LOS PAÍSES DE EUROPA CON MÁS DE 5M DE HABITANTES.

SELECT * FROM COUNTRY 
WHERE 
	POPULATION > 5000000 AND
	CONTINENT = "EUROPE";

# EJ2 - MUESTRA EL NOMBRE DE LOS PAÍSES CON MÁS DE 80M DE HABITANTES.

SELECT NAME FROM COUNTRY WHERE POPULATION > 80000000;

# EJ3 - MUESTRA LOS PAÍSES CUYA JEFA DE ESTADO ERA ISABEL II.

SELECT * FROM COUNTRY WHERE HEADOFSTATE = "ELISABETH II";

# EJ4 - SELECCIONA LAS DISTINTAS REGIONES DE EUROPA;

SELECT DISTINCT REGION FROM COUNTRY WHERE CONTINENT = "EUROPE";

# EJ5 - SELECCIONA LOS DISTRITOS EN QUE SE DIVIDE ESPAÑA (TABLA CITY)

SELECT DISTINCT DISTRICT FROM CITY WHERE COUNTRYCODE = "ESP";

# FUNCIÓN COUNT

SELECT COUNT(*) FROM COUNTRY WHERE CONTINENT = "EUROPE";

# EJ6 - ¿CUÁNTOS PAÍSES DE EUROPA ESTÁN EN EL SUR?

SELECT COUNT(*) FROM COUNTRY WHERE REGION = "SOUTHERN EUROPE";

# EJ7 - ¿CUÁNTOS PAÍSES AFRICANOS TIENEN MÁS DE 50M HABITANTES?

SELECT COUNT(*) FROM COUNTRY 
WHERE CONTINENT = "AFRICA" AND POPULATION > 50000000;

# EJ8 - ¿CUÁNTAS CIUDADES DE ALEMANIA HAY EN LA BBDD?

SELECT COUNT(*) FROM CITY WHERE COUNTRYCODE = "DEU";

# EJ9 - ¿QUÉ IDIOMAS SE HABLAN EN ESPAÑA DE FORMA OFICIAL?

SELECT LANGUAGE FROM COUNTRYLANGUAGE WHERE COUNTRYCODE = "ESP" AND ISOFFICIAL="T";

# EJ10 - ¿EN QUÉ PAISES EL ESPAÑOL ES LENGUA OFICIAL?

SELECT * FROM COUNTRYLANGUAGE WHERE LANGUAGE = "SPANISH" AND ISOFFICIAL="T";

# EJ11 - ¿CUÁNTAS CIUDADES DE ESPAÑA TIENEN MÁS DE 1M DE HABITANTES?

SELECT COUNT(*) FROM CITY WHERE COUNTRYCODE="ESP" AND POPULATION > 1000000;


# ORDENAR UN RESULTADO

# ORDER BY {COLUMNA A ORDENAR}
# DESC -> DESCENDENTE
# ASC -> ASCENDENTE

SELECT * FROM COUNTRY ORDER BY SURFACEAREA DESC; -- ASC

# EJ12 - ¿CUÁL ES EL PAÍS MÁS POBLADO DEL MUNDO?

SELECT NAME FROM COUNTRY ORDER BY POPULATION DESC; -- ASC

# EJ13 - ¿CUÁL ES EL PAÍS MÁS POBLADO DE EUROPA?

SELECT NAME FROM COUNTRY WHERE CONTINENT = "EUROPE" ORDER BY POPULATION DESC; -- ASC

# EJ14 - MUESTRA LAS REGIONES DE NORTEAMÉRICA ORDENADAS ALFABÉTICAMENTE

SELECT DISTINCT REGION FROM COUNTRY WHERE CONTINENT = "NORTH AMERICA" ORDER BY REGION;

# EJ15 - MUESTRA LAS 5 CIUDADES MÁS POBLADAS DE ESPAÑA.

SELECT NAME FROM CITY WHERE COUNTRYCODE="ESP" ORDER BY POPULATION DESC LIMIT 5;

# EJ16 - ¿CUÁLES SON LOS PAÍSES DEL MUNDO CON NÚMERO DE HABITANTES ENTRE 1M Y 5M?

SELECT NAME FROM COUNTRY WHERE POPULATION BETWEEN 1000000 AND 5000000;

# EJ17 - ¿CUÁL ES EL PAÍS DEL CARIBE CON MAYOR ESPERANZA DE VIDA?

SELECT NAME FROM COUNTRY WHERE REGION = "CARIBBEAN" ORDER BY LIFEEXPECTANCY DESC LIMIT 1;

# EJ18 - ¿QUÉ PAÍSES TIENEN MENOS DE 60 AÑOS DE ESPERANZA DE VIDA?

SELECT NAME FROM COUNTRY WHERE LIFEEXPECTANCY < 60;

# EJ19 - MUESTRA UNA LISTA DE LAS FORMAS DE GOBIERNO ORDENADA DE FORMA ALFABÉTICA

SELECT DISTINCT GovernmentForm FROM COUNTRY ORDER BY GovernmentForm;

# EJ20 - ¿CUÁL ES EL PAÍS DE AMÉRICA CON MAYOR SUPERFICIE?

SELECT NAME FROM COUNTRY WHERE CONTINENT="NORTH AMERICA" OR CONTINENT="SOUTH AMERICA" ORDER BY SURFACEAREA DESC LIMIT 1;

SELECT NAME FROM COUNTRY WHERE CONTINENT IN ("NORTH AMERICA", "SOUTH AMERICA") ORDER BY SURFACEAREA DESC LIMIT 1;

SELECT NAME FROM COUNTRY WHERE CONTINENT LIKE "%AMERICA%" ORDER BY SURFACEAREA DESC LIMIT 1;

# EJ21 - MUESTRA LOS PAÍSES QUE SON ALGÚN TIPO DE MONARQUÍA

SELECT NAME FROM COUNTRY WHERE GovernmentForm LIKE "%MONARCHY%";

# EJ22 - CUÁNTOS PAÍSES COMIENZAN POR LA LETRA 'A'

SELECT COUNT(*) FROM COUNTRY WHERE NAME LIKE "A%";

# EJ23 - MUESTRA UNA LISTA DE LOS TIPOS DE REPÚBLICAS QUE HAY, ORDENADA DE FORMA ALFABÉTICA

SELECT DISTINCT GovernmentForm 
FROM COUNTRY 
WHERE GovernmentForm LIKE "%REPUBLIC%" 
ORDER BY GovernmentForm;

# EJ24 MUESTRA LOS 5 PAÍSES CON MENOR ESPERANZA DE VIDA

SELECT NAME FROM COUNTRY 
WHERE LIFEEXPECTANCY IS NOT NULL 
ORDER BY LIFEEXPECTANCY
LIMIT 5;

# EJ25 ¿CUÁNTOS PAÍSES TIENEN FECHA DE INDEPENDENCIA?

SELECT COUNT(*) FROM COUNTRY WHERE INDEPYEAR IS NOT NULL;
SELECT COUNT(INDEPYEAR) FROM COUNTRY;

# EJ26 ¿PARA CUÁNTOS PAÍSES NO DISPONEMOS DEL DATO DE ESPERANZA DE VIDA?

SELECT COUNT(*) FROM COUNTRY WHERE LIFEEXPECTANCY IS NULL;

# EJ27 ¿CUÁNTAS REGIONES HAY?

SELECT COUNT(DISTINCT REGION) AS REGIONES FROM COUNTRY;

# OPERACIONES

SELECT "DATO" AS COLUMNA;

SELECT 2*2 AS PRODUCTO;

SELECT 2/2 AS DIVISIÓN;

SELECT 2%2 AS "MÓDULO O RESTO";

SELECT NAME, POPULATION*POPULATION AS POPULATION_2 FROM COUNTRY;

# EJ28 MUESTRA UNA LISTA DE PAÍSES Y SU DENSIDAD DE POBLACIÓN

SELECT NAME, POPULATION/SURFACEAREA AS "DENSIDAD DE POBLACIÓN" FROM COUNTRY;

# EJ29 MUESTRA EL PRODUCTO NACIONAL BRUTO (GNP) PER CÁPITA DE ARGENTINA

# EJ30 MUESTRA EL PAÍS MÁS DENSAMENTE POBLADO DEL MUNDO

# EJ31 MUESTRA LOS 5 PAÍSES MÁS GRANDES (POR SUPERFICIE) DE EUROPA

# EJ32 MUESTRA LOS 5 PAÍSES MÁS DENSAMENTE POBLADOS DE EUROPA

# EJ33 MUESTRA LOS 5 PAÍSES MENOS DENSAMENTE POBLADOS DE EUROPA
