USE SAKILA;

SELECT * FROM FILM;

# EJ1 MUESTRA LA PELÍCULA MÁS LARGA

SELECT TITLE, LENGTH FROM FILM WHERE LENGTH = (SELECT MAX(LENGTH) FROM FILM);

# EJ2 MUESTRA LA PELÍCULA MAS CORTA

SELECT TITLE, LENGTH FROM FILM WHERE LENGTH = (SELECT MIN(LENGTH) FROM FILM);

# EJ3 MUESTRA LOS DISTINTOS RATING DE EDAD USADOS

SELECT DISTINCT RATING
FROM FILM;

# EJ4 CUÁNTAS PELICULAS DURAN MÁS DE 2 HORAS

SELECT COUNT(*)
FROM FILM
WHERE LENGTH > 120;

# EJ5 MUESTRA EL NOMBRE DE LAS PELÍCULAS Y SU DURACIÓN EN HORAS (ORDENA DE MENOR A MAYOR DURACIÓN) 

SELECT TITLE, LENGTH/60 AS DURACION_HORAS FROM FILM
ORDER BY LENGTH ASC;

# EJ6 ¿CUÁNTAS PELÍCULAS CONTIENEN ESCENAS ELIMINADAS?

SELECT COUNT(*) FROM FILM WHERE SPECIAL_FEATURES LIKE "%DELETED SCENES%";

# EJ7 ¿QUÉ PELICULAS TIENEN "ALIEN", EN SU NOMBRE?

SELECT * FROM FILM WHERE TITLE LIKE "%ALIEN%" ORDER BY TITLE;


# EJ8 ¿CUAL ES LA PELICULA MÁS LARGA QUE PODEMOS VER POR MENOS DE 1$ (RENTAL_RATE)?

SELECT TITLE, LENGTH FROM FILM WHERE RENTAL_RATE < 1 AND LENGTH = (SELECT MAX(LENGTH) FROM FILM WHERE RENTAL_RATE < 1);

# EJ9 ¿CUÁNTAS PELICULAS SON DOCUMENTALES? (COLUMNA DESCRIPTION)

SELECT COUNT(*) FROM FILM WHERE DESCRIPTION LIKE "%DOCUMENTARY%";

# EJ10 ¿CUÁL ES EL PRECIO DE REMPLAZO MEDIO DE LAS PELICULAS CON RATING "R"?

SELECT AVG (REPLACEMENT_COST) FROM FILM WHERE RATING = "R";

# EJ 11 ¿CUANTOS DIAS TARDARÍAMOS EN VER TODAS LAS PELICULAS? ¿Y AÑOS?

SELECT SUM(LENGTH)/60/24 FROM FILM; 
