CREATE SCHEMA RESTAURANTE;
USE RESTAURANTE;

CREATE TABLE CATEGORIA (
	NOMBRE VARCHAR(30) PRIMARY KEY,
    DESCRIPCION TINYTEXT
);

# PLATO (NOMBRE, DESCRIPCIÓN, FOTO, PRECIO, NOMBRE_CATEGORÍA)

CREATE TABLE PLATO (
	NOMBRE VARCHAR(30) PRIMARY KEY,
    DESCRIPCION TINYTEXT,
    FOTO MEDIUMBLOB,
    PRECIO DECIMAL(5,2),
    NOMBRE_CATEGORIA VARCHAR(30),
    
    FOREIGN KEY (NOMBRE_CATEGORIA) REFERENCES CATEGORIA(NOMBRE)
);

#RECETA (CÓDIGO, TIEMPO_ELABORACIÓN, DIFICULTAD, NOMBRE_PLATO)

CREATE TABLE RECETA (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    TIEMPO_ELABORACION TIME,
    DIFICULTAD VARCHAR(10),
    NOMBRE_PLATO VARCHAR(30),
    FOREIGN KEY (NOMBRE_PLATO) REFERENCES PLATO(NOMBRE)
);

#INGREDIENTE (NOMBRE, FOTO, STOCK)

CREATE TABLE INGREDIENTE(
	NOMBRE VARCHAR(30) PRIMARY KEY,
    FOTO MEDIUMBLOB,
    STOCK DECIMAL(5,2)
);
#RECETA_USA_INGREDIENTE (CÓDIGO, NOMBRE, CANTIDAD, UNIDAD DE MEDIDA)

CREATE TABLE RECETA_USA_INGREDIENTE(
	CODIGO INT ,   
    NOMBRE VARCHAR(30),
    CANTIDAD DECIMAL(5,2),
    UNIDAD_DE_MEDIDA VARCHAR(15),
    
    PRIMARY KEY (CODIGO, NOMBRE),
    
    FOREIGN KEY (CODIGO) REFERENCES RECETA(CODIGO),
    FOREIGN KEY (NOMBRE) REFERENCES INGREDIENTE(NOMBRE)
)