DROP SCHEMA IF EXISTS PROYECTOS;
CREATE SCHEMA PROYECTOS;
USE PROYECTOS;

CREATE TABLE EMPLEADO (
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    FECHA_CONTRATACIÓN DATE, 
    SALARIO DECIMAL(6,2)
);

CREATE TABLE PROYECTO (
	NOMBRE VARCHAR(50) PRIMARY KEY, 
    FECHA_INICIO DATE, 
    FECHA_FIN DATE, 
    PRESUPUESTO DECIMAL(9,2), 
    DESCRIPCIÓN MEDIUMTEXT
);

CREATE TABLE DEPARTAMENTO (
	NOMBRE VARCHAR(50) PRIMARY KEY, 
    UBICACIÓN VARCHAR(50), 
    PRESUPUESTO DECIMAL(9,2), 
    DNI_JEFE CHAR(9),
    
    FOREIGN KEY (DNI_JEFE) REFERENCES EMPLEADO(DNI)
);

CREATE TABLE DEPARTAMENTO_DIRIGE_PROYECTO (
	DEPARTAMENTO VARCHAR(50), 
    PROYECTO VARCHAR(50),
    
    PRIMARY KEY(DEPARTAMENTO, PROYECTO),
    
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(NOMBRE),
    FOREIGN KEY (PROYECTO) REFERENCES PROYECTO(NOMBRE)
);

CREATE TABLE EMPLEADO_MONITORIZA_DEPARTAMENTO_PROYECTO (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    DNI_EMPLEADO CHAR(9), 
    DEPARTAMENTO VARCHAR(50), 
    PROYECTO VARCHAR(50), 
    FECHA_INICIO DATE, 
    FECHA_FIN DATE,
    
    UNIQUE(DNI_EMPLEADO, DEPARTAMENTO, PROYECTO, FECHA_INICIO),
    
    FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI),
    FOREIGN KEY (DEPARTAMENTO, PROYECTO) REFERENCES DEPARTAMENTO_DIRIGE_PROYECTO(DEPARTAMENTO, PROYECTO)
)
