DROP SCHEMA IF EXISTS TIENDA;
CREATE SCHEMA TIENDA;
USE TIENDA;

CREATE TABLE SECCION (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50),
    NIF_DIRECTOR CHAR(9)
);

INSERT INTO SECCION VALUES
(DEFAULT, "EQUIPOS", NULL);

CREATE TABLE EMPLEADO (
	NIF CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50) NOT NULL, 
    APELLIDOS VARCHAR(50) NOT NULL, 
    ID_SECCION INT NOT NULL,
    FOREIGN KEY (ID_SECCION) REFERENCES SECCION(ID)
);

INSERT INTO EMPLEADO VALUES
("1234667L", "JOSELITO", "XANXE", 1),
("8934667L", "MANUELA", "XANXE", 1);

# ALTER TABLE SECCION ADD COLUMN NIF_DIRECTOR CHAR(9);

ALTER TABLE SECCION ADD CONSTRAINT FOREIGN KEY (NIF_DIRECTOR) REFERENCES EMPLEADO(NIF);

CREATE TABLE CLIENTE (
	NIF CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    APELLIDOS VARCHAR(50), 
    DOMICILIO VARCHAR(50), 
    CIUDAD VARCHAR(50), 
    PROVINCIA VARCHAR(50), 
    TELEFONO VARCHAR(15) UNIQUE,
    CONSTRAINT NIF_CORRECTO CHECK (NIF REGEXP "[0-9]{8}[A-Z]")
);

INSERT INTO CLIENTE (NIF, NOMBRE) VALUES
("78945625K", "FRAN");

CREATE TABLE ARTICULO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT
);

INSERT INTO ARTICULO VALUES
(DEFAULT),
(DEFAULT),
(DEFAULT),
(DEFAULT);

CREATE TABLE CLIENTE_COMPRA_ARTICULO (
	NIF_CLIENTE CHAR(9),
    CODIGO_ARTICULO INT,
    FECHA_HORA_COMPRA DATETIME, 
    CANTIDAD SMALLINT, 
    NIF_EMPLEADO CHAR(9),
    PRIMARY KEY(NIF_CLIENTE, CODIGO_ARTICULO, FECHA_HORA_COMPRA),
    FOREIGN KEY (NIF_CLIENTE) REFERENCES CLIENTE(NIF),
    FOREIGN KEY (CODIGO_ARTICULO) REFERENCES ARTICULO(CODIGO),
    FOREIGN KEY (NIF_EMPLEADO) REFERENCES EMPLEADO(NIF)
);

CREATE TABLE EQUIPO (
	CODIGO INT PRIMARY KEY,
    STOCK SMALLINT,
    NOMBRE VARCHAR(50),
    DESCRIPCION MEDIUMTEXT,
    PRECIO DECIMAL(7,2) DEFAULT 0.00,
    FOREIGN KEY (CODIGO) REFERENCES ARTICULO(CODIGO)
);

INSERT INTO EQUIPO VALUES
(1, 5, "MIPESE", "", 200.99);

CREATE TABLE COMPONENTE (
	CODIGO INT PRIMARY KEY,
    STOCK SMALLINT,
    NOMBRE VARCHAR(50),
    DESCRIPCION MEDIUMTEXT,
    PRECIO DECIMAL(7,2),
    FOREIGN KEY (CODIGO) REFERENCES ARTICULO(CODIGO)
);

INSERT INTO COMPONENTE VALUES
(2, 5, "GRAFICASA", "", 200.99),
(3, 10, "LO RAM", "", 20.99),
(4, 200, "RATON", "", 5);

CREATE TABLE EQUIPO_COMPUESTO_COMPONENTE (
	CODIGO_EQUIPO INT, 
    CODIGO_COMPONENTE INT, 
    CANTIDAD SMALLINT,
    PRIMARY KEY(CODIGO_EQUIPO, CODIGO_COMPONENTE),
    FOREIGN KEY (CODIGO_EQUIPO) REFERENCES EQUIPO(CODIGO),
    FOREIGN KEY (CODIGO_COMPONENTE) REFERENCES COMPONENTE(CODIGO)
);

INSERT INTO EQUIPO_COMPUESTO_COMPONENTE VALUES
(1, 2, 1),
(1, 3, 2),
(1, 4, 1);

INSERT INTO CLIENTE_COMPRA_ARTICULO VALUES
("78945625K", 1, "2023-10-26 09:55:00", 1, "1234667L"),
("78945625K", 4, "2023-10-26 09:55:00", 3, "1234667L");

# INSERTA DOS EMPLEADOS
# INSERTA UNA SECCION (ASÍGNALE UN DIRECTOR NULO)
# INSERTA UN CLIENTE
# INSERTA UN EQUIPO COMPUESTO POR TRES COMPONENTES
# EL CLIENTE COMPRA UNO DE ESOS EQUIPOS Y 3 COMPONENTES IGUALES