DROP SCHEMA IF EXISTS CICLISTAS;
CREATE SCHEMA CICLISTAS;

USE CICLISTAS;

#EJERCICIO 3

#CICLISTA (DNI, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO)
CREATE TABLE CICLISTA (
	DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR (50),
    NACIONALIDAD VARCHAR(40),
    FECHA_NACIMIENTO DATE
);

#EQUIPO (NOMBRE, NACIONALIDAD, NOMBRE_DIRECTOR)
CREATE TABLE EQUIPO (
	NOMBRE VARCHAR(50) PRIMARY KEY,
    NACIONALIDAD VARCHAR(40),
    NOMBRE_DIRECTOR VARCHAR(50)
);

#PRUEBA (NOMBRE, AÑO, NUMERO_ETAPAS, KM_TOTALES, DNI_GANADOR)
CREATE TABLE PRUEBA(
	NOMBRE VARCHAR(50),
    ANIO SMALLINT,
    NUMERO_ETAPAS TINYINT,
    KM_TOTALES SMALLINT, #DECIMAL(6,2)
    DNI_GANADOR CHAR(9),
    
    PRIMARY KEY (NOMBRE, ANIO),
    FOREIGN KEY (DNI_GANADOR) REFERENCES CICLISTA(DNI)
    
);

#CICLISTA_PERTENECE_EQUIPO (DNI_CICLISTA, NOMBRE_EQUIPO, FECHA_INICIO, FECHA_FIN)
CREATE TABLE CICLISTA_PERTENECE_EQUIPO (
	DNI_CICLISTA CHAR(9),
    NOMBRE_EQUIPO VARCHAR(50),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    
    PRIMARY KEY (DNI_CICLISTA, NOMBRE_EQUIPO, FECHA_INICIO),
    FOREIGN KEY (DNI_CICLISTA) REFERENCES CICLISTA(DNI),
    FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO(NOMBRE)
    
); 

#EQUIPO_PARTICIPA_PRUEBA (NOMBRE_EQUIPO, NOMBRE_PRUEBA, AÑO_PRUEBA, PUESTO)

CREATE TABLE EQUIPO_PARTICIPA_PRUEBA (
	NOMBRE_EQUIPO VARCHAR(50),
	NOMBRE_PRUEBA VARCHAR(50),
    ANIO_PRUEBA SMALLINT,
    PUESTO SMALLINT,
    
    PRIMARY KEY (NOMBRE_EQUIPO, NOMBRE_PRUEBA, ANIO_PRUEBA),
    FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO(NOMBRE),
    FOREIGN KEY (NOMBRE_PRUEBA, ANIO_PRUEBA) REFERENCES PRUEBA(NOMBRE, ANIO)
);

# ============================== INSERTAR DATOS ============================== #

INSERT INTO CICLISTA VALUES
("12345678H", "FULANO", "ESPAÑOL", "2000-08-08"),
("12345679H", "MEN-GALO", "FRANCÉS", "2000-08-08"),
("12345676H", "PIRATA", "INGLÉS", "2000-08-08");

INSERT INTO EQUIPO VALUES
("ALPINO", "SUIZA", "ADOLFO");

#PRUEBA (NOMBRE, AÑO, NUMERO_ETAPAS, KM_TOTALES, DNI_GANADOR)

INSERT INTO PRUEBA VALUES
("VUELTA", 2002, 56, 4000, NULL),
("VUELTA", 2003, 56, 4000, "12345676H");

#CICLISTA_PERTENECE_EQUIPO (DNI_CICLISTA, NOMBRE_EQUIPO, FECHA_INICIO, FECHA_FIN)
INSERT INTO CICLISTA_PERTENECE_EQUIPO VALUES
("12345676H", "ALPINO", "2008-01-01", "2008-12-31"),
("12345676H", "ALPINO", "2009-01-01", "2009-12-31");

#EQUIPO_PARTICIPA_PRUEBA (NOMBRE_EQUIPO, NOMBRE_PRUEBA, AÑO_PRUEBA, PUESTO)
INSERT INTO EQUIPO_PARTICIPA_PRUEBA VALUES
("ALPINO", "VUELTA", 2003, 5);

SELECT * FROM EQUIPO_PARTICIPA_PRUEBA;









