DROP SCHEMA IF EXISTS FABRICAS;
CREATE SCHEMA FABRICAS;
USE FABRICAS;

CREATE TABLE CLIENTE (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    SALDO DECIMAL(9,2) DEFAULT 0.00, 
    DESCUENTO DECIMAL(3,2),
    CONSTRAINT DESCUENTO_0_1 CHECK (DESCUENTO BETWEEN 0 AND 1)
);

CREATE TABLE DIRECCION (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO SMALLINT,
    CALLE VARCHAR(50),
    PUEBLO VARCHAR(50),
    CIUDAD VARCHAR(50)
);

CREATE TABLE PEDIDO (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    FECHA_HORA DATETIME, 
    ID_CLIENTE INT, 
    ID_DIRECCION INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID)
);

CREATE TABLE ARTICULO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION MEDIUMTEXT NOT NULL
);

CREATE TABLE FABRICA (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    TELEFONO CHAR(9) UNIQUE, 
    TOTAL_ARTICULOS SMALLINT
);

CREATE TABLE CLIENTE_TIENE_DIRECCION (
	ID_CLIENTE INT, 
    ID_DIRECCION INT,
    PRIMARY KEY (ID_CLIENTE, ID_DIRECCION),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID)
);

CREATE TABLE PEDIDO_CONTIENE_ARTICULO (
	ID_PEDIDO INT, 
    ID_ARTICULO INT, 
    CANTIDAD SMALLINT,
    PRIMARY KEY (ID_PEDIDO, ID_ARTICULO),
	FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID),
    FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID)
);

CREATE TABLE FABRICA_PROVEE_ARTICULO(
	ID_FABRICA INT, 
    ID_ARTICULO INT, 
    STOCK SMALLINT UNSIGNED,
	PRIMARY KEY (ID_FABRICA, ID_ARTICULO),
	FOREIGN KEY (ID_FABRICA) REFERENCES FABRICA(ID),
    FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID),
    CONSTRAINT STOCK_POSITIVO CHECK (STOCK>0)
);
    