DROP SCHEMA IF EXISTS ZOO;
CREATE SCHEMA ZOO;
USE ZOO;

# RESTRICCIONES:
#	- DESCRIPCIÓN Y NOMBRE COMÚN NO PUEDEN SER NULOS
#   - EL CLIMA POR DEFECTO ES "SOLEADO"
#   - EL TIEMPO DEL RECORRIDO DEBE SER MAYOR DE 30 MINUTOS
#   - LA LONGITUD DEL RECORRIDO NO PUEDE SER NEGATIVA
#   - EL ÍNIDICE DE VULNERABILIDAD ES UN NÚMERO ENTRE 0 Y 10
    
CREATE TABLE ESPECIE(
	NOMBRE_CIENTIFICO VARCHAR(50) PRIMARY KEY,
    DESCRIPCION MEDIUMTEXT NOT NULL,
    FOTO MEDIUMBLOB
);

INSERT INTO ESPECIE VALUES
("MUSTELA PUTORIUS FURO", "MUSTÉLIDO DOMESTICADO", NULL);

CREATE TABLE ESPECIE_TIENE_NOMBRE_COMUN(
	NOMBRE_CIENTIFICO VARCHAR(50),
    NOMBRE_COMUN VARCHAR(50) NOT NULL,
    
    PRIMARY KEY (NOMBRE_CIENTIFICO, NOMBRE_COMUN),
    FOREIGN KEY (NOMBRE_CIENTIFICO) REFERENCES ESPECIE(NOMBRE_CIENTIFICO)
);

CREATE TABLE RECORRIDO(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    LONGITUD DECIMAL(5,2) UNSIGNED,
    TIEMPO TIME,
    MAXIMO_VISITANTES MEDIUMINT,
    
    CONSTRAINT TIEMPO_MAYOR CHECK (TIEMPO>"00:30:00"),
    CONSTRAINT LONGITUD_POSITIVA CHECK (LONGITUD>0)
);

INSERT INTO RECORRIDO VALUES
(DEFAULT, 300, "00:50:00", 40);

CREATE TABLE HABITAT(
	NOMBRE VARCHAR(50) PRIMARY KEY,
    CLIMA VARCHAR(50) DEFAULT "SOLEADO", 
    VEGETACION VARCHAR(50), 
    CODIGO_RECORRIDO INT,
    
    FOREIGN KEY (CODIGO_RECORRIDO) REFERENCES RECORRIDO(CODIGO)
);

INSERT INTO HABITAT VALUES
("BOSQUE CONTINENTAL", "TEMPLADO", "MATORRAL", 1);

CREATE TABLE ESPECIE_VIVE_HABITAT(
	NOMBRE_CIENTIFICO VARCHAR(50),
    NOMBRE_HABITAT VARCHAR(50), 
    INDICE_VULNERABILIDAD TINYINT,
    
    PRIMARY KEY (NOMBRE_CIENTIFICO, NOMBRE_HABITAT),
    FOREIGN KEY (NOMBRE_CIENTIFICO) REFERENCES ESPECIE(NOMBRE_CIENTIFICO),
    FOREIGN KEY (NOMBRE_HABITAT) REFERENCES HABITAT(NOMBRE),
    CONSTRAINT VULNERABILIDAD_0_10 CHECK (INDICE_VULNERABILIDAD BETWEEN 0 AND 10)
);

INSERT INTO ESPECIE_VIVE_HABITAT VALUES
("MUSTELA PUTORIUS FURO", "BOSQUE CONTINENTAL", 3);

SELECT * FROM ESPECIE;


