DROP SCHEMA IF EXISTS CARRERAS;
CREATE SCHEMA CARRERAS;
USE CARRERAS;

CREATE TABLE PARTICIPANTE (
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50)
);

CREATE TABLE ORGANIZADOR (
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    EDAD TINYINT, 
    CARGO VARCHAR(50), 
    FECHA_INICIO DATETIME
);

CREATE TABLE ORGANIZADOR_DIRECTOR (
	DNI_DIRECTOR CHAR(9) PRIMARY KEY, 
    CURRÍCULUM MEDIUMBLOB,
    
    FOREIGN KEY (DNI_DIRECTOR) REFERENCES ORGANIZADOR(DNI)
);

CREATE TABLE CARRERA (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    FECHA DATE, 
    LUGAR_INICIO VARCHAR(50), 
    LUGAR_FIN VARCHAR(50), 
    DNI_DIRECTOR CHAR(9),
    
    FOREIGN KEY (DNI_DIRECTOR) REFERENCES ORGANIZADOR_DIRECTOR(DNI_DIRECTOR)
);

CREATE TABLE ETAPA (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NÚMERO_ETAPA TINYINT, 
    KILÓMETROS_TOTALES SMALLINT, 
    ID_CARRERA INT,
    
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE CARRERA_A_PIE (
	ID_CARRERA INT PRIMARY KEY, 
    DESNIVEL FLOAT,
    
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE CARRERA_CICLISTA (
	ID_CARRERA INT PRIMARY KEY, 
    TEMPERATURA FLOAT, 
    LLUEVE BOOLEAN,
    
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE BICICLETA (
	ID INT PRIMARY KEY, 
    MODELO VARCHAR(50), 
    ES_ELÉCTRICA BOOLEAN, 
    PESO FLOAT
);

CREATE TABLE PARTICIPANTE_PARTICIPA_CARRERA (
	DNI_PARTICIPANTE CHAR(9), 
    ID_CARRERA INT, 
    NÚMERO_DORSAL SMALLINT,
    
    PRIMARY KEY (DNI_PARTICIPANTE, ID_CARRERA),
    FOREIGN KEY (DNI_PARTICIPANTE) REFERENCES PARTICIPANTE(DNI),
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE ORGANIZADOR_ASISTE_CARRERA(
    DNI_ORGANIZADOR CHAR(9), 
    ID_CARRERA INT,
     
	PRIMARY KEY (DNI_ORGANIZADOR, ID_CARRERA),
    FOREIGN KEY (DNI_ORGANIZADOR) REFERENCES ORGANIZADOR(DNI),
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE CARRERA_CICLISTA_PERMITE_BICICLETA (
	ID_CARRERA_CICLISTA INT, 
    ID_BICICLETA INT,
    
    PRIMARY KEY (ID_CARRERA_CICLISTA, ID_BICICLETA),
    FOREIGN KEY (ID_CARRERA_CICLISTA) REFERENCES CARRERA_CICLISTA(ID_CARRERA),
    FOREIGN KEY (ID_BICICLETA) REFERENCES BICICLETA(ID)
);

# CREA UNA CARRERA CICLISTA CON 3 ETAPAS, 2 PARTICIPANTES, 3 ORGANIZADORES, 1 DIRECTOR Y 2 BICICLETAS PERMITIDAS




 