# RESTRICCIONES:
# - USANDO EXPRESIONES REGURLARES, VALIDA EL DNI Y LA MATRÍCULA DEL VEHÍCULO
# - LAS CUANTÍAS DEBEN SER POSITIVAS

DROP SCHEMA IF EXISTS SEGUROS;
CREATE SCHEMA SEGUROS;
USE SEGUROS;

CREATE TABLE CLIENTE (
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    FECHA_NACIMIENTO DATE, 
    FECHA_PERMISO DATE,
    
    CONSTRAINT DNI_VÁLIDO CHECK (DNI RLIKE "[0-9]{8}[A-Z]")
);

CREATE TABLE VEHÍCULO (
	NÚMERO_BASTIDOR CHAR(17) PRIMARY KEY, 
	MATRÍCULA VARCHAR(8), 
    MARCA VARCHAR(50), 
    MODELO VARCHAR(50), 
    COLOR VARCHAR(20), 
    FECHA_1_MATRICULACIÓN DATE,
    

    CONSTRAINT MATRÍCULA_VÁLIDA CHECK 
    (MATRÍCULA RLIKE "[A-Z]{2}[0-9]{4}[A-Z]{2}" 
	OR MATRÍCULA RLIKE "[0-9]{4}[BCDFGHJKLMNPQRSTVWXYZ]{3}")
);

INSERT INTO VEHÍCULO (NÚMERO_BASTIDOR, MATRÍCULA) 
VALUES
("123", "GR0000BG"),
("1237", "0000ZBG");

SELECT * FROM VEHÍCULO;

CREATE TABLE CLIENTE_ASEGURA_VEHÍCULO (
	DNI_CLIENTE CHAR(9), 
    NÚMERO_BASTIDOR_VEHÍCULO CHAR(17),
    
    PRIMARY KEY(DNI_CLIENTE, NÚMERO_BASTIDOR_VEHÍCULO),
    
    FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI),
    FOREIGN KEY (NÚMERO_BASTIDOR_VEHÍCULO) REFERENCES VEHÍCULO(NÚMERO_BASTIDOR)
);

CREATE TABLE PÓLIZA (
	NÚMERO_PÓLIZA INT PRIMARY KEY AUTO_INCREMENT, 
    PRECIO DECIMAL(6,2), 
    DNI_CLIENTE CHAR(9), 
    NÚMERO_BASTIDOR_VEHÍCULO CHAR(17),
    
    FOREIGN KEY (DNI_CLIENTE, NÚMERO_BASTIDOR_VEHÍCULO) REFERENCES CLIENTE_ASEGURA_VEHÍCULO (DNI_CLIENTE, NÚMERO_BASTIDOR_VEHÍCULO),
    
    CONSTRAINT PRECIO_MAS_0 CHECK (PRECIO>0)
);

CREATE TABLE COBERTURA (
	CÓDIGO INT PRIMARY KEY AUTO_INCREMENT, 
    TIPO VARCHAR(50), 
    CUANTÍA DECIMAL(6,2)
);

CREATE TABLE SINIESTRO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE, 
    LUGAR VARCHAR(50), 
    CAUSA VARCHAR(50), 
    CUANTÍA DECIMAL(6,2), 
    NÚMERO_PÓLIZA INT
);

CREATE TABLE PÓLIZA_ASOCIA_COBERTURA (
	NÚMERO_PÓLIZA INT, 
    CÓDIGO_COBERTURA INT,
    
    PRIMARY KEY (NÚMERO_PÓLIZA, CÓDIGO_COBERTURA),
    
    FOREIGN KEY (NÚMERO_PÓLIZA) REFERENCES PÓLIZA(NÚMERO_PÓLIZA),
    FOREIGN KEY (CÓDIGO_COBERTURA) REFERENCES COBERTURA(CÓDIGO)
);