DROP SCHEMA IF EXISTS AVIONES;
CREATE SCHEMA AVIONES;
USE AVIONES;

# RESTRICCIONES:
# 	1.- LOS DIAS DE LA SEMANA SOLO PUEDEN SER "LUNES", "MARTES", ETC.
#	2.- LA CAPACIDAD DE LOS AVIONES ESTARA ENTRE 2 Y 200
#	3.- NINGUN VALOR PUEDE SER NULO
#	4.- EL NOMBRE DEL AEROPUERTO DEBE SER UNICO
#	5.- LAS PLAZAS VACIAS DE LOS AVIONES SON 10 POR DEFECTO
#	6.- LA FECHA DE VUELO DEBE SER POSTERIOR AL 1 DE ENERO DE 1930

CREATE TABLE AEROPUERTO (
	CODIGO CHAR(3) PRIMARY KEY, 
    NOMBRE VARCHAR(50) UNIQUE NOT NULL, 
    CIUDAD VARCHAR(50) NOT NULL, 
    PAIS VARCHAR(50) NOT NULL 
);

INSERT INTO AEROPUERTO VALUES
("GRX", "AEROPUERTO GRANADA", "GRANADA", "ESPAÑITA"),
("JAN", "AEROPUERTO JAÉN", "JAÉN", "ESPAÑITA");

CREATE TABLE PROGRAMA_VUELO (
	COMPANIA VARCHAR(50) NOT NULL, 
    RUTA VARCHAR(50) NOT NULL, 
    CODIGO_DESPEGUE CHAR(3) NOT NULL, 
    CODIGO_ATERRIZAJE CHAR(3) NOT NULL,
    
    PRIMARY KEY(COMPANIA, RUTA),
    FOREIGN KEY (CODIGO_DESPEGUE) REFERENCES AEROPUERTO(CODIGO),
    FOREIGN KEY (CODIGO_ATERRIZAJE) REFERENCES AEROPUERTO(CODIGO)
);

INSERT INTO PROGRAMA_VUELO VALUES
("VUELING", "GRX-JAN", "GRX", "JAN");

CREATE TABLE PROGRAMA_VUELO_DIA (
	COMPANIA VARCHAR(50) NOT NULL, 
    RUTA VARCHAR(50) NOT NULL,
    DIA ENUM("LUNES", "MARTES", "MIÉRCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO"),
    
    PRIMARY KEY (COMPANIA, RUTA, DIA),
    FOREIGN KEY(COMPANIA, RUTA) REFERENCES PROGRAMA_VUELO(COMPANIA, RUTA),
    
    CONSTRAINT DIA_OK CHECK ( DIA IN ("LUNES", "MARTES", "MIÉRCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO") )
);

INSERT INTO PROGRAMA_VUELO_DIA VALUES
("VUELING", "GRX-JAN", "LUNES"),
("VUELING", "GRX-JAN", "MARTES"),
("VUELING", "GRX-JAN", "MIÉRCOLES");

CREATE TABLE MODELO_AVION (
	NOMBRE VARCHAR(50) PRIMARY KEY, 
    CAPACIDAD SMALLINT NOT NULL,
    CONSTRAINT CAPACIDAD_2_200 CHECK (CAPACIDAD BETWEEN 2 AND 200)
);

INSERT INTO MODELO_AVION VALUES
("BOEING 747", 200);

CREATE TABLE VUELO (
	NUMERO_VUELO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    PLAZAS_VACIAS SMALLINT DEFAULT 10 NOT NULL,
    COMPANIA VARCHAR(50) NOT NULL,
    RUTA VARCHAR(50) NOT NULL,
    NOMBRE_MODELO VARCHAR(50) NOT NULL,
    
    FOREIGN KEY(COMPANIA, RUTA) REFERENCES PROGRAMA_VUELO(COMPANIA, RUTA),
    FOREIGN KEY (NOMBRE_MODELO) REFERENCES MODELO_AVION(NOMBRE),
    CONSTRAINT FECHA_MAS_1930 CHECK (FECHA > "1930-01-01")
);

INSERT INTO VUELO VALUES
(DEFAULT, "2023-11-02", 3, "VUELING", "GRX-JAN", "BOEING 747");

CREATE TABLE MODELO_AVION_PUEDE_ATERRIZAR_EN_AEROPUERTO(
	NOMBRE_MODELO VARCHAR(50) NOT NULL, 
    CODIGO_AEROPUERTO CHAR(3) NOT NULL,
    
    PRIMARY KEY(NOMBRE_MODELO, CODIGO_AEROPUERTO),    
    FOREIGN KEY (CODIGO_AEROPUERTO) REFERENCES AEROPUERTO(CODIGO),
    FOREIGN KEY (NOMBRE_MODELO) REFERENCES MODELO_AVION(NOMBRE)
)


