DROP SCHEMA IF EXISTS ONGs;
CREATE SCHEMA ONGs;
USE ONGs;

CREATE TABLE SEDE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    PAIS VARCHAR(50) NOT NULL,
    CIUDAD VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) UNIQUE NOT NULL DEFAULT "000000000",
    DIRECTOR VARCHAR(50)
);

INSERT INTO SEDE (PAIS, CIUDAD, DIRECCION, TELEFONO) VALUES
("ESPAÑA", "GRANADA", "UNA CALLE", "659659659"),
("ESPAÑA", "GRANADA", "UNA CALLE", "759659659");

CREATE TABLE PROYECTO(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    PRESUPUESTO DECIMAL(9,2) DEFAULT 10000,
    RESPONSABLE VARCHAR(50),
    ID_SEDE INT,
    
    FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID),
    
    CONSTRAINT FECHA_FIN_POSTERIOR CHECK (FECHA_FIN>FECHA_INICIO)
);

INSERT INTO PROYECTO VALUES
(DEFAULT, "LO QUE SEA", "2023-10-20", "2024-10-20", DEFAULT, NULL, 1);

SELECT * FROM PROYECTO;

CREATE TABLE POBLACION(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    PAIS VARCHAR(50),
    NUMERO_HABITANTES INT
);

CREATE TABLE ACTUACION(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION MEDIUMTEXT,
    INVERSION DECIMAL(9,2), 
    CODIGO_PROYECTO INT, 
    ID_POBLACION INT,
    
    FOREIGN KEY (CODIGO_PROYECTO) REFERENCES PROYECTO(CODIGO),
    FOREIGN KEY (ID_POBLACION) REFERENCES POBLACION(ID)
);


