DROP SCHEMA IF EXISTS COCHES;
CREATE SCHEMA COCHES;
USE COCHES;

CREATE TABLE MARCA (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50)
);

CREATE TABLE MODELO (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50),
    ID_MARCA INT,
    
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID)
);

CREATE TABLE VERSIÓN (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50),
    POTENCIA SMALLINT, 
    PRECIO DECIMAL(9,2), 
    COMBUSTIBLE VARCHAR(30), 
    ID_MODELO INT,
    
	FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID)
);

CREATE TABLE EXTRA (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50),
    DESCRIPCIÓN MEDIUMTEXT
);

CREATE TABLE CLIENTE (
	NIF CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    DIRECCIÓN VARCHAR(50), 
    TELÉFONO VARCHAR(15)
);

CREATE TABLE VENDEDOR (
	NIF CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    DIRECCIÓN VARCHAR(50), 
    TELÉFONO VARCHAR(15)
);

CREATE TABLE VERSIÓN_EQUIPA_EXTRA (
	ID_VERSIÓN INT, 
    ID_EXTRA INT, 
    PRECIO DECIMAL(9,2),
    
    PRIMARY KEY(ID_VERSIÓN, ID_EXTRA),
    
    FOREIGN KEY (ID_VERSIÓN) REFERENCES VERSIÓN(ID),
    FOREIGN KEY (ID_EXTRA) REFERENCES EXTRA(ID)
);

CREATE TABLE CLIENTE_COMPRA_MODELO (
	NIF_CLIENTE CHAR(9), 
    ID_MODELO INT, 
    FECHA_COMPRA DATE, 
    MATRÍCULA VARCHAR(10),
    NIF_VENDEDOR CHAR(9),
    
    PRIMARY KEY (NIF_CLIENTE, ID_MODELO, MATRÍCULA),
    
    FOREIGN KEY (NIF_CLIENTE) REFERENCES CLIENTE(NIF),
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID),
    FOREIGN KEY (NIF_VENDEDOR) REFERENCES VENDEDOR(NIF)
);