DROP SCHEMA IF EXISTS HOSPITAL;
CREATE SCHEMA HOSPITAL;
USE HOSPITAL;

CREATE TABLE APARATO (
	NOMBRE VARCHAR(50) PRIMARY KEY, 
    ES_ELÉCTRICO BOOLEAN, 
    ES_FUNGIBLE BOOLEAN
);

CREATE TABLE PRUEBA (
	CÓDIGO INT PRIMARY KEY AUTO_INCREMENT, 
	NOMBRE_APARATO VARCHAR(50),
    
    FOREIGN KEY (NOMBRE_APARATO) REFERENCES APARATO(NOMBRE) 
);

CREATE TABLE PACIENTE (
	NÚMERO_SS CHAR(12) PRIMARY KEY, 
    DNI CHAR(9) UNIQUE, 
    NOMBRE VARCHAR(50), 
    FECHA_NACIMIENTO DATE
);

CREATE TABLE ESPECIALISTA (
	NÚMERO_COLEGIADO INT PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    ESPECIALIDAD VARCHAR(50)
);

CREATE TABLE HABITACIÓN (
	PLANTA TINYINT, 
    NÚMERO SMALLINT,
    PRIMARY KEY(PLANTA, NÚMERO)
);

CREATE TABLE CAMA (
	NÚMERO INT PRIMARY KEY AUTO_INCREMENT, 
    TIPO VARCHAR(50), 
    PLANTA TINYINT, 
    NÚMERO_HABITACIÓN SMALLINT,
    
    FOREIGN KEY (PLANTA, NÚMERO_HABITACIÓN) REFERENCES HABITACIÓN(PLANTA, NÚMERO)
);

CREATE TABLE ESPECIALISTA_REALIZA_PRUEBA_PACIENTE (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NÚMERO_COLEGIADO INT, 
    CÓDIGO_PRUEBA INT, 
    NÚMERO_SS CHAR(12), 
    FECHA_HORA DATETIME,
    
    UNIQUE(NÚMERO_COLEGIADO, CÓDIGO_PRUEBA, NÚMERO_SS, FECHA_HORA),
    
    FOREIGN KEY (NÚMERO_COLEGIADO) REFERENCES ESPECIALISTA(NÚMERO_COLEGIADO),
    FOREIGN KEY (CÓDIGO_PRUEBA) REFERENCES PRUEBA(CÓDIGO),
    FOREIGN KEY (NÚMERO_SS) REFERENCES PACIENTE(NÚMERO_SS)
);

CREATE TABLE PACIENTE_INGRESA_HABITACIÓN_CAMA (
	NÚMERO_SS CHAR(12), 
    NÚMERO_CAMA INT, 
    FECHA_INGRESO DATE, 
    FECHA_ALTA DATE,
    
    PRIMARY KEY(NÚMERO_SS, NÚMERO_CAMA, FECHA_INGRESO),
    
    FOREIGN KEY (NÚMERO_SS) REFERENCES PACIENTE(NÚMERO_SS),
    FOREIGN KEY (NÚMERO_CAMA) REFERENCES CAMA(NÚMERO)
)