DROP SCHEMA IF EXISTS POKEMONS;
CREATE SCHEMA POKEMONS;
USE POKEMONS;

CREATE TABLE ENTRENADOR (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50), 
    EDAD TINYINT
);

INSERT INTO ENTRENADOR (NOMBRE, EDAD) VALUES
("ASH", 30),
("KETCHUP", 15),
("OAK", 75);

CREATE TABLE POKEMON (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50) NOT NULL, 
    TIPO VARCHAR(50) NOT NULL, 
    NIVEL TINYINT NOT NULL, 
    ID_ENTRENADOR INT, 
    FECHA_HORA_CAPTURA DATETIME, 
    POKEBALLS_USADAS TINYINT,
    
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID),
    CONSTRAINT LIMITE_POKEBALLS CHECK (POKEBALLS_USADAS BETWEEN 1 AND 5)
);

INSERT INTO POKEMON VALUES
(DEFAULT, "CHARMANDER", "FUEGITO DEL INSTA", 14, 1, "2023-05-15", 2),
(DEFAULT, "CHARMANDER", "FUEGITO DEL INSTA", 14, 1, "2023-05-15", 3),
(DEFAULT, "CHARMANDER", "FUEGITO DEL INSTA", 14, 2, "2023-05-15", 5),
(DEFAULT, "CHARMANDER", "FUEGITO DEL INSTA", 14, 2, "2023-05-15", 1),
(DEFAULT, "CHARMANDER", "FUEGITO DEL INSTA", 14, 3, "2023-05-15", 2),
(DEFAULT, "CHARMANDER", "FUEGITO DEL INSTA", 14, 3, "2023-05-15", 2);

SELECT * FROM POKEMON;

CREATE TABLE GIMNASIO (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50) UNIQUE, 
    CIUDAD VARCHAR(50) DEFAULT "CIUDAD ESMERALDA", 
    ID_LIDER INT,
    
    FOREIGN KEY (ID_LIDER) REFERENCES ENTRENADOR(ID)
);

INSERT INTO GIMNASIO VALUES
(DEFAULT, "GIMNASIO VERDE", DEFAULT, 3);

CREATE TABLE MEDALLA (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    FECHA_OBTENCION DATE, 
    NOMBRE VARCHAR(50), 
    ID_ENTRENADOR INT, 
    ID_GIMNASIO INT,
    
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID),
    FOREIGN KEY (ID_GIMNASIO) REFERENCES GIMNASIO(ID)
);

INSERT INTO MEDALLA	VALUES
(DEFAULT, "2023-05-05", "MEDALLA VERDE", 1, 1),
(DEFAULT, "2022-07-15", "MEDALLA VERDE", 3, 1);

CREATE TABLE ENTRENADOR_DESAFIA_GINMASIO (
	ID_ENTRENADOR INT, 
    ID_GIMNASIO INT, 
    FECHA DATE,
    
    PRIMARY KEY(ID_ENTRENADOR, ID_GIMNASIO, FECHA),
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID),
    FOREIGN KEY (ID_GIMNASIO) REFERENCES GIMNASIO(ID)
);

INSERT INTO ENTRENADOR_DESAFIA_GINMASIO VALUES
(1,1,"2022-06-09"),
(2,1,"2023-06-09"),
(3,1,"2023-08-20");

# CREA 3 ENTRENADORES Y 1 GIMNASIO.
# UNO DE LOS ENTRENADORES DEBE DE LIDERAR EL GIMNASIO.
# CADA ENTRENADOR DEBE DE HABER CAPTURADO 2 POKEMONS
# TODOS LOS ENTRENADORES HAN DESAFÍADO AL GIMNASIO ALGUNA VEZ.
# EL LÍDER Y OTRO ENTRENADOR HAN OBTENIDO LA MEDALLA DE ESE GIMNASIO.



