DROP SCHEMA IF EXISTS HOBBITS;
CREATE SCHEMA HOBBITS;
USE HOBBITS;

CREATE TABLE CRIATURA (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50),
    EDAD SMALLINT
);

CREATE TABLE HOBBIT (
	ID_CRIATURA INT PRIMARY KEY, 
    NOMBRE_FAMILIA VARCHAR(50), 
    PIE_NO_CALZA TINYINT, 
    DISTANCIA_COMARCA FLOAT,
    
	FOREIGN KEY (ID_CRIATURA) REFERENCES CRIATURA(ID)
);

CREATE TABLE HOMBRE (
	ID_CRIATURA INT PRIMARY KEY, 
    DESTREZA VARCHAR(50),
    
    FOREIGN KEY (ID_CRIATURA) REFERENCES CRIATURA(ID)
);

CREATE TABLE ENANO (
	ID_CRIATURA INT PRIMARY KEY, 
    CARGA_MÁXIMA FLOAT, 
    ESTATURA FLOAT, 
    LONGITUD_BARBA FLOAT,
    
    FOREIGN KEY (ID_CRIATURA) REFERENCES CRIATURA(ID)
);

CREATE TABLE ELFO (
	ID_CRIATURA INT PRIMARY KEY,  
    DISTANCIA_TIRO FLOAT,
    
    FOREIGN KEY (ID_CRIATURA) REFERENCES CRIATURA(ID)
);

CREATE TABLE MAGO (
	ID_CRIATURA INT PRIMARY KEY, 
    
    FOREIGN KEY (ID_CRIATURA) REFERENCES CRIATURA(ID)
);

CREATE TABLE COMPAÑÍA (
	NOMBRE VARCHAR(50) PRIMARY KEY,
    LUGAR VARCHAR(50), 
    FECHA_FORMACIÓN DATE, 
    FECHA_DISOLUCIÓN DATE, 
    ID_HOMBRE INT, 
    ID_ENANO INT, 
    ID_ELFO INT, 
    ID_MAGO INT,
    
    FOREIGN KEY (ID_HOMBRE) REFERENCES HOMBRE(ID_CRIATURA),
    FOREIGN KEY (ID_ENANO) REFERENCES ENANO(ID_CRIATURA),
    FOREIGN KEY (ID_ELFO) REFERENCES ELFO(ID_CRIATURA),
    FOREIGN KEY (ID_MAGO) REFERENCES MAGO(ID_CRIATURA)
);

CREATE TABLE ANILLO (
	NOMBRE VARCHAR(50) PRIMARY KEY,
    INSCRIPCIÓN VARCHAR(50), 
    FECHA_CREACIÓN DATE
);

CREATE TABLE COMPAÑÍA_TIENE_HOBBIT (
	NOMBRE VARCHAR(50), 
    ID_HOBBIT INT,
    NOMBRE_ANILLO VARCHAR(50), 
    TIEMPO_PORTADO TIME,
    
    PRIMARY KEY(NOMBRE, ID_HOBBIT),
    
    FOREIGN KEY (NOMBRE) REFERENCES COMPAÑÍA(NOMBRE),
    FOREIGN KEY (NOMBRE_ANILLO) REFERENCES ANILLO(NOMBRE),
    FOREIGN KEY (ID_HOBBIT) REFERENCES HOBBIT(ID_CRIATURA)
);

CREATE TABLE CRIATURA_LIDERA_COMPAÑIA (
	ID_CRIATURA INT, 
    NOMBRE_COMPAÑIA VARCHAR(50), 
    FECHA_INICIO DATE, 
    FECHA_FIN DATE,
    
    PRIMARY KEY(ID_CRIATURA, NOMBRE_COMPAÑIA, FECHA_INICIO),
    FOREIGN KEY (ID_CRIATURA) REFERENCES CRIATURA(ID),
    FOREIGN KEY (NOMBRE_COMPAÑIA) REFERENCES COMPAÑÍA(NOMBRE)
)