DROP SCHEMA IF EXISTS VILLAQUIÉN;
CREATE SCHEMA VILLAQUIÉN;
USE VILLAQUIÉN;

CREATE TABLE QUIÉN (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50), 
    EDAD TINYINT
);

INSERT INTO QUIÉN VALUES
(DEFAULT, "ROSA", 30),
(DEFAULT, "MARGARITA", 30),
(DEFAULT, "VIOLETA", 30),
(DEFAULT, "MALVA", 30);

CREATE TABLE QUIÉN_VILLAQUIÉN (
	ID_QUIÉN INT PRIMARY KEY, 
    OFICIO VARCHAR(50),
    DIRECCIÓN VARCHAR(50),
    
    FOREIGN KEY (ID_QUIÉN) REFERENCES QUIÉN(ID)
);

INSERT INTO QUIÉN_VILLAQUIÉN VALUES
(1, "CARPINTERO", "SU CASA"),
(2, "CARPINTERO", "SU CASA"),
(3, "CARPINTERO", "SU CASA");

CREATE TABLE EL_GRINCH (
	ID_QUIÉN INT PRIMARY KEY, 
    NOMBRE_MASCOTA VARCHAR(50) DEFAULT "MAX", 
    COLOR_PELO VARCHAR(50) DEFAULT "VERDE",
    
    FOREIGN KEY (ID_QUIÉN) REFERENCES QUIÉN(ID),
    CONSTRAINT ES_VERDE CHECK (COLOR_PELO="VERDE"),
    CONSTRAINT ES_MAX CHECK (NOMBRE_MASCOTA="MAX")
);

INSERT INTO EL_GRINCH VALUES
(4, "MAX", "VERDE");

CREATE TABLE REGALO (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50), 
    PRECIO DECIMAL(6,2)
);

INSERT INTO REGALO VALUES
(DEFAULT, "OBJETO", "0"),
(DEFAULT, "VIAJE", "0"),
(DEFAULT, "WALKMAN", "0"),
(DEFAULT, "PELOTA", "0"),
(DEFAULT, "HUESO", "0");

CREATE TABLE OBJETO (
	ID_REGALO INT PRIMARY KEY, 
    PESO FLOAT,
    MATERIAL VARCHAR(50),
    
    FOREIGN KEY (ID_REGALO) REFERENCES REGALO(ID)
);

INSERT INTO OBJETO VALUES
(1, 200, "MADERA");

CREATE TABLE EXPERIENCIA (
	ID_REGALO INT PRIMARY KEY, 
    DURACIÓN TIME, 
    UBICACIÓN VARCHAR(50), 
    FECHA_CADUCIDAD DATE,
    
    FOREIGN KEY (ID_REGALO) REFERENCES REGALO(ID)
);

INSERT INTO EXPERIENCIA VALUES
(2, "200:00", "VILLAWHO", "2023-05-01");

CREATE TABLE ELECTRÓNICA (
	ID_REGALO INT PRIMARY KEY, 
    BATERÍA BOOLEAN,
    
    FOREIGN KEY (ID_REGALO) REFERENCES REGALO(ID)
);

INSERT INTO ELECTRÓNICA VALUES
(3, TRUE);

CREATE TABLE JUGUETE_PERRO (
	ID_REGALO INT PRIMARY KEY, 
    TAMAÑO VARCHAR(50), 
    DURABILIDAD VARCHAR(50),
    
    FOREIGN KEY (ID_REGALO) REFERENCES REGALO(ID)
);

INSERT INTO JUGUETE_PERRO VALUES
(4, "GRANDE", "POCO"),
(5, "PEQUEÑO", "MUCHO");

CREATE TABLE QUIÉN_RECIBE_REGALO (
	ID_QUIÉN INT, 
    ID_REGALO INT, 
    FECHA_HORA DATETIME,
    
    PRIMARY KEY (ID_QUIÉN, ID_REGALO, FECHA_HORA),
    FOREIGN KEY (ID_QUIÉN) REFERENCES QUIÉN_VILLAQUIÉN(ID_QUIÉN),
    FOREIGN KEY (ID_REGALO) REFERENCES REGALO(ID)
);

INSERT INTO QUIÉN_RECIBE_REGALO VALUES
(1, 1, "2022-12-25"),
(2, 2, "2022-12-25"),
(3, 3, "2022-12-25");

CREATE TABLE GRINCH_COMPRA_JUGUETE_PERRO (
	ID_GRINCH INT, 
	ID_REGALO INT,
    
    PRIMARY KEY(ID_GRINCH, ID_REGALO),
    FOREIGN KEY (ID_GRINCH) REFERENCES EL_GRINCH(ID_QUIÉN),
    FOREIGN KEY (ID_REGALO) REFERENCES JUGUETE_PERRO(ID_REGALO)
    
);

INSERT INTO GRINCH_COMPRA_JUGUETE_PERRO VALUES
(4, 4),
(4, 5);

CREATE TABLE GRINCH_ROBA_REGALO_A_QUIÉN (
	ID_GRINCH INT, 
    ID_QUIÉN INT, 
    ID_REGALO INT, 
    FECHA_HORA DATETIME,
    
    PRIMARY KEY (ID_GRINCH, ID_QUIÉN, ID_REGALO, FECHA_HORA),
    
    FOREIGN KEY (ID_GRINCH) REFERENCES EL_GRINCH(ID_QUIÉN),
    FOREIGN KEY (ID_QUIÉN, ID_REGALO, FECHA_HORA)
		REFERENCES QUIÉN_RECIBE_REGALO(ID_QUIÉN, ID_REGALO, FECHA_HORA)
    
);

INSERT INTO GRINCH_ROBA_REGALO_A_QUIÉN VALUES
(4, 1, 1, "2022-12-25"),
(4, 2, 2, "2022-12-25"),
(4, 3, 3, "2022-12-25");